### ISSUE TITLE
Some characters aren't compressing right.

### ISSUE THREAD

**Issue by AmazingMech2418** [amazinigmech2418/File-Compressor#1]
Some spaces are compressing and extracting to become "@"s.

**Comment by AmazingMech2418** [comment]
@kyleplo

**Comment by AmazingMech2418** [comment]
Can someone help? @SkyanSam @towerofnix @kyleplo

**Comment by towerofnix** [comment]
You are definitely not giving enough details in this for me to help you (and probably not anyone else who's not very acquainted with the code).

Exactly *what* spaces are "compressing and extracting"? Spaces in return data from fetches? (Which fetches?) Spaces in the actual source code file..? (Where?) What do you mean by "compressing and extracting"?

edit: ..Actually this isn't in scratchOn, whoops. So some of those questions don't make sense.

It's very difficult for me to help you with your code, because I just don't understand how it works: You haven't given *any* documentation at all, anywhere, which would help me know what it does or give me any idea as to why it's not working. The README is fairly empty and there are no comments at all in the code.

You see, I didn't write your code. You did. You're the only one who has any idea how it works. I have to make *guesses* as to what it does, when you ask me, and this is very difficult for me, because I just don't know where to start. If you want help from me, or from anyone, you need to make sure you're writing your code in such a way that other people *can* help you - you need to provide documentation as to what the program is, how to use it, and especially how the code works.

For example, you say this is a program to compress files, and I see that there's some code to actually do that compression -- but you're the only one who knows how it works. You should document that code, explaining what `numberMap` is and how it is a part of compressing the file. That way other people (or even you!) can compare the code to your documentation and then figure out what might be going wrong.

**Comment by AmazingMech2418** [comment]
@towerofnix It works by converting text to a numbermap, converting every number into binary, joining binary strings, and getting character codes from that binary and converting to a string. A numbermap is an array of character codes in a string from ObjectifyJS. The spaces are in the file to compress.

**Comment by AmazingMech2418** [comment]
@narulacodes

**Comment by radioblahaj** [comment]
Yes?
